### ISSUE TITLE
Frequent termination during operation.

### ISSUE THREAD

**Issue by Elowen-jjw** [seahorn/seahorn#491] opened 2023-06-22 15:52 UTC
Now I am writing a program in Java to run and check 100 c files at one time. I set a time limit of 20s. If it exceeds 20s, the check of the file will be automatically ended and the next file will be checked. But during this process, my computer will frequently end the running Java IDE. I have installed it in two ways (docker and clang compilation of developer's zone), and both of them have this kind of crash. Please help me to explain this situation, thanks.

Command line: sea pf -m64 testFile.c
OS: ubuntu 22.04

**Comment by caballa** [comment] 2023-06-22 15:57
I'm not sure I understand your problem. You mean that the seahorn crashes and the error is propagated up and kills your IDE? If you are running each seahorn run in a thread then you should be able to see that the thread is crashing and move on with the next one.

**Comment by Elowen-jjw** [comment] 2023-07-04 12:14
Thank you for your reply. We are confirming whether it is because of our improper use of threads and optimizing our code accordingly.

**Comment by caballa** [comment] 2023-07-04 17:01
I'll close it for now. Feel free to re-open it if you think the problem is caused by SeaHorn

**Closed by caballa** 2023-07-04 17:01 UTC

**Comment by Elowen-jjw** [comment] 2023-07-06 12:05
I took care of that. It was my fault. I'm sorry to bother you.
