### ISSUE TITLE
[seapp] mixed semantics pass crashing

### ISSUE THREAD

**Issue by danblitzhou** [seahorn/seahorn#247] opened 2019-11-11 23:54 UTC
Seapp crashed during mixed semantics pass when processing a C++ file from trusty.
Exact command used:
`path/to/seapp --simplifycfg-sink-common=false -o tmp_bc/out.pp.ms.bc --horn-mixed-sem --ms-reduce-main -S tmp_bc/out.pp.bc`
First displayed warnings about some deconstructor function declarations not having `!dbg attachment`
```
function declaration may not have a !dbg attachment
void (%"struct.keymaster::KeymasterMessage"*)* @_ZN9keymaster16KeymasterMessageD0Ev
function declaration may not have a !dbg attachment
void (%"class.keymaster::KeymasterContext"*)* @_ZN9keymaster12SerializableD0Ev
function declaration may not have a !dbg attachment
void (%"class.keymaster::KeymasterContext"*)* @_ZN9keymaster6LoggerD0Ev
```

Crashing stack trace:
```
seapp: /home/x245zhou/workplace/seahorn/ext/llvm/lib/IR/Verifier.cpp:4681: virtual bool (anonymous namespace)::VerifierLegacyPass::doFinalization(llvm::Module &): Assertion `!V->hasBrokenDebugInfo() && "Module contains invalid debug info"' failed.
#0 0x0000000002b78e79 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/x245zhou/workplace/seahorn/ext/llvm/lib/Support/Unix/Signals.inc:398:11
#1 0x0000000002b79029 PrintStackTraceSignalHandler(void*) /home/x245zhou/workplace/seahorn/ext/llvm/lib/Support/Unix/Signals.inc:462:1
#2 0x0000000002b77713 llvm::sys::RunSignalHandlers() /home/x245zhou/workplace/seahorn/ext/llvm/lib/Support/Signals.cpp:49:16
#3 0x0000000002b793a4 SignalHandler(int) /home/x245zhou/workplace/seahorn/ext/llvm/lib/Support/Unix/Signals.inc:252:1
#4 0x00007fac75e6d890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
#5 0x00007fac74916e97 gsignal /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
#6 0x00007fac74918801 abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:81:0
#7 0x00007fac7490839a __assert_fail_base /build/glibc-OTsEL5/glibc-2.27/assert/assert.c:89:0
#8 0x00007fac74908412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)
#9 0x0000000001b13a8f (anonymous namespace)::VerifierLegacyPass::doFinalization(llvm::Module&) /home/x245zhou/workplace/seahorn/ext/llvm/lib/IR/Verifier.cpp:4682:5
#10 0x0000000001a5b9a1 llvm::FPPassManager::doFinalization(llvm::Module&) /home/x245zhou/workplace/seahorn/ext/llvm/lib/IR/LegacyPassManager.cpp:1553:16
#11 0x0000000001a5c29c (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/x245zhou/workplace/seahorn/ext/llvm/lib/IR/LegacyPassManager.cpp:1609:16
#12 0x0000000001a5bb33 llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/x245zhou/workplace/seahorn/ext/llvm/lib/IR/LegacyPassManager.cpp:1694:16
#13 0x0000000001a5c541 llvm::legacy::PassManager::run(llvm::Module&) /home/x245zhou/workplace/seahorn/ext/llvm/lib/IR/LegacyPassManager.cpp:1725:3
#14 0x000000000140dcfd (anonymous namespace)::SeaPassManagerWrapper::run(llvm::Module&) /home/x245zhou/workplace/seahorn/debug-build/../tools/seapp/seapp.cc:285:36
#15 0x000000000140d98a main /home/x245zhou/workplace/seahorn/debug-build/../tools/seapp/seapp.cc:647:14
#16 0x00007fac748f9b97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#17 0x000000000140b02a _start (/home/x245zhou/workplace/seahorn/debug-build/run/bin/seapp+0x140b02a)
Stack dump:
0.      Program arguments: /home/x245zhou/workplace/seahorn/debug-build/run/bin/seapp --simplifycfg-sink-common=false -o tmp_bc/out.pp.ms.bc --horn-mixed-sem --ms-reduce-main -S tmp_bc/out.pp.bc
```
Example .pp.bc file: https://1drv.ms/u/s!ArXNCZL2VjKCgfcfqgt-dqyEZP_mWA?e=X6FHWD or https://gist.github.com/danblitzhou/5ed865ad2949faf06d4ca798b5aa6332

**Comment by caballa** [comment] 2019-11-12 01:24
This a small example found by @igcontreras that triggers the same error:

```
extern void sea_dsa_alias(const void *p, ...);
extern void __VERIFIER_error (void);
extern void __VERIFIER_assume (int);
#define assume __VERIFIER_assume
#define sassert(X) (void)((X) || (__VERIFIER_error (), 0))

extern int nd_int(void);

void ldv_stop(void){
  while(1);  
}
void main() {
  int a = 0;
  ldv_stop();
  sassert(a < 0);
}
```
The command is `sea pf -g`.
The problem arises only with the option `-g` and due to the infinite loop in `ldv_stop`.
I can see that the problem is that after we drop all references from dead blocks in `reduceToRegion`
https://github.com/seahorn/seahorn/blob/master/lib/Transforms/Utils/Local.cc#L74

We end up with this and I think the problem is `!dbg !9`:
```
declare !dbg !9 internal fastcc void @ldv_stop() unnamed_addr #0
```
Note that I just modified this part of the code in previous commit 211098214a154c928ea8f3eb523eb688bfb4c371 but this problem was before the commit so I think they are independent.

**Comment by agurfinkel** [comment] 2019-11-12 01:28
Fixed via 86861e

**Closed by agurfinkel** 2019-11-12 01:28 UTC
Labels: bug

**Comment by agurfinkel** [comment] 2019-11-12 01:30
empty functions are declarations and should not have metadata. We had this in mixed semantics but not in `Local.cc`. Triggered by functions that are reduced to nothing by our transformation. Now fixed.

There might be latent bug that we replace functions with infinite loops by declarations. Technically infinite loops are undefined behavior in C so best strategy is debatable. Such functions should be marked `noreturn`, in which case we will be fine.
