### ISSUE TITLE
Seahorn crashes on example with  "-g --inline"  flags

### ISSUE THREAD

**Issue by dannyrasin** [seahorn/seahorn#73] opened 2017-08-28 20:24 UTC
When I use Seahorn with both “-g” and “--inline” flags on the example, below, Seahorn crashes (And prints the stack trace).
When either of the two flags is removed, the run terminates with a correct result (sat).
The complete command I used was:
sea pf -g --inline seahorn_crash_example.c
-----------------------------------------------------------------------------------------------------------------
#include "seahorn.h"

int havoc_int();

int comm4 = 0;
int p = 1;

void second()
{
  if (havoc_int())
  {
    comm4 = havoc_int();
  }
}

void first(int new_p)
{
  int comm4_COPY = comm4;
  p = new_p;

  comm4 = havoc_int();
  __VERIFIER_assume(comm4 == comm4_COPY);
  if (havoc_int())
  {
    __VERIFIER_assume((comm4 == 1) || (p != 1));
  }
}

int main()
{
  first(1);
  second();
  sassert(comm4 == 1);
  while (1)
  {
    first(2);
    second();
  }
}

**Comment by caballa** [comment] 2017-08-30 02:42
This is the bitcode [test-crash.pp.bc.zip](https://github.com/seahorn/seahorn/files/1262298/test-crash.pp.bc.zip) and the command that reproduces the crash:

`seapp -o ./test-crash.pp.ms.bc --horn-mixed-sem --ms-reduce-main ./test-crash.pp.bc`

**Comment by caballa** [comment] 2017-08-30 02:47
Hi Dan,
Arie already replied to you but I just mention it here for other people.

While we fix this problem, you might want to try with the branch `llvm-3.8`. This branch replaces llvm 3.6 with 3.8.

**Comment by dannyrasin** [comment] 2017-08-30 10:36
Hi Jorge,
Thanks a lot for checking this so quickly!

**Comment by caballa** [comment] 2017-09-13 16:56
Since we have moved to llvm 3.8 this error does not happen anymore so I will close this issue.

**Closed by caballa** 2017-09-13 16:56 UTC
Labels: bug
