### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by MikolasJanota** [seahorn/seahorn#441] opened 2022-07-14 18:34 UTC
**Describe the bug**
Unable to build the project.

**To Reproduce**
Follow instructions in the installation readme. It seems to have trouble downloading llvm. 

**Expected behavior**
Project built

**Logs, Stacktraces, and Screenshots**

```
$ cmake --build .
Scanning dependencies of target llvm
[  5%] Creating directories for 'llvm'
[ 11%] Performing download step (SVN checkout) for 'llvm'
svn: E170011: Repository moved temporarily to 'https://llvm.org/svn/llvm-project/llvm/tags/RELEASE_500/final'
make[2]: *** [CMakeFiles/llvm.dir/build.make:92: llvm-prefix/src/llvm-stamp/llvm-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:278: CMakeFiles/llvm.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Desktop (please complete the following information):**
 - OS: ubuntu as Win10 VM
 - LLVM: n/a
 - Z3:   4.8.18 (But it seems to me that the build is not picking up on it)

**Comment by caballa** [comment] 2022-07-14 18:48
It looks that you are using `master` branch which is a very old one.
The active development branch is `dev10`.

**Comment by caballa** [comment] 2022-07-14 18:54
Btw, the easiest way to install SeaHorn is via docker (https://github.com/seahorn/seahorn/issues/440#issuecomment-1154036025).
If you don't want to use docker, just install `llvm-10` in your machine. `cmake` might be able to find it automatically if `llvm-10` is installed in a common path. Otherwise, you can pass the `cmake` option `-DLLVM_DIR=<LLVM_INSTALL_DIR>/bin/cmake/llvm`

**Comment by MikolasJanota** [comment] 2022-07-21 09:47
> The easiest way to install SeaHorn is via docker [#440 (comment)](https://github.com/seahorn/seahorn/issues/440#issuecomment-1154036025). If you don't want to use docker, you can install vanilla `llvm-10` in your machine. `cmake` might be able to find it automatically if `llvm-10` is installed in a common path. Otherwise, you can pass the `cmake` option `-DLLVM_DIR=<YOUR_LLVM_INSTALL_DIR>/bin/cmake/llvm`

One day I might figure out what's docker and maybe even install it but that they has not come yet.

The installation for dev10 seems to have worked even though there were some complaints about lit, which I presume is not critical?

However, there seems to be something wrong with the installation because it doesn't seem to be capable of inferring invariants:

```
$ ./sea pf --crab --cex=cex.xml --show-invars -m64 t1.c
/usr/bin/clang-10 -c -emit-llvm -D__SEAHORN__ -fdeclspec -O1 -Xclang -disable-llvm-optzns -fgnu89-inline -m64 -Iinclude -o /tmp/sea-8r7u5z0r/t1.bc t1.c
/home/mikolas/git/seahorn/build/run/bin/seapp -o /tmp/sea-8r7u5z0r/t1.pp.bc --simplifycfg-sink-common=false --strip-extern=false --promote-assumptions=false --kill-vaarg=true --horn-keep-arith-overflow=false /tmp/sea-8r7u5z0r/t1.bc
/home/mikolas/git/seahorn/build/run/bin/seapp --simplifycfg-sink-common=false -o /tmp/sea-8r7u5z0r/t1.pp.ms.bc --horn-mixed-sem --ms-reduce-main /tmp/sea-8r7u5z0r/t1.pp.bc
/home/mikolas/git/seahorn/build/run/bin/seaopt -f --simplifycfg-sink-common=false -o /tmp/sea-8r7u5z0r/t1.pp.ms.o.bc -O3 --seaopt-enable-indvar=false --seaopt-enable-loop-idiom=false --unroll-threshold=150 --unroll-allow-partial=false --unroll-partial-threshold=0 --vectorize-loops=false --disable-slp-vectorization=true /tmp/sea-8r7u5z0r/t1.pp.ms.bc
/home/mikolas/git/seahorn/build/run/bin/seahorn --horn-crab --keep-shadows=true --sea-dsa=ci --horn-solve --horn-answer -horn-cex-pass -horn-cex=cex.xml -horn-inter-proc -horn-sem-lvl=mem --horn-step=large /tmp/sea-8r7u5z0r/t1.pp.ms.o.bc
CLAM WARNING: Call to external function val. Havocing the return value and possibly its modified memory regions if the pointer analysis models the external function
sat
main@_2
main@_2 --> main@verifier.error.split
main@verifier.error.split --> query!0

$ cat t1.c
#include "seahorn/seahorn.h"

extern int val();

int main() {
  const int s = val();
  if (s > 10) return 0;
  int i = 0;
  while (i < s) i++;
  sassert(i==s);
  return 0;
}
```

**Comment by caballa** [comment] 2022-07-21 14:39
Regarding the example you shared:

```
#include "seahorn/seahorn.h"

extern int val();

int main() {
  const int s = val();
  if (s > 10) return 0;
  int i = 0;
  while (i < s) i++;
  sassert(i==s);
  return 0;
}
```

SeaHorn returns `sat` which means that it couldn't prove the program is safe. In fact, the program is not safe since `val` can return a negative number.  If you try this program:

```
#include "seahorn/seahorn.h"

extern int val(void);

int main() {
  const int s = val();
  if (s < 0) return 0;
  if (s > 10) return 0;
  int i = 0;
  while (i < s) i++;
  sassert(i==s);
  return 0;
}
```

SeaHorn outputs:

```
unsat
Function: main
main@entry: true
main@_2: ((main@%.01.i+(-1*main@%_0))<=0)
main@verifier.error.split: false
```
Now, it outputs `unsat` meaning that the program satisfies the assertions.
The invariants are expressed in terms of the LLVM bitcode analyzed. To get that bitcode, you need to add the option `-oll=program.ll` 

I hope this helps.

**Comment by caballa** [comment] 2022-07-21 14:41
The python package `lit` is only needed to run the regression tests.

**Comment by MikolasJanota** [comment] 2022-07-21 20:21
Right. I realized my mistake shortly after, so I removed it but it still somehow got to you :)

Probably getting out of scope of the original question, any chance to derive non-liner invariants, e.g. arithmetic progression? E.g. 

```
#include "seahorn/seahorn.h"

extern int val();

int main() {
  const int n = val();
  if (n < 0 || n > 100) return 0;
  int s = 0;
  for (int i = 0; i < n; i++) s += i;
  sassert(2*s == n*(n-1));
  return 0;
}
```

**Comment by caballa** [comment] 2022-07-21 20:24
No, SeaHorn invariant capabilities are mostly limited to linear invariants.

**Comment by caballa** [comment] 2022-07-22 15:08
I'll close this issue. Feel free to open new issue if you have more questions.

**Closed by caballa** 2022-07-22 15:08 UTC
Labels: installation, usage
